### PR TITLE
[Docs] remove duplicated content from .yaml pages

### PR DESCRIPTION
**Pull request by ryancurtis1**
- Removes duplicated content on pages with descriptions from both openapi .yaml files and markdown files.

- [x] TODO: review added markdown files as sources to Kapa.ai

### CODE REVIEW

**Review by junhouse — COMMENTED** [review]
nice, looking good! Were you able to verify that the `mdx` files and `description` section of the open API are the same?

**Comment by ryancurtis1** [comment]
> nice, looking good! Were you able to verify that the `mdx` files and `description` section of the open API are the same?

Almost all of them are the same or the `description` section of the open API is a subset of the content in the `mdx` files with three exceptions: `Query Retention Report`, `Query Profiles`, and `JQL`

Synced with Myron, MD should be the source of truth for most files but it seems that for these three exceptions the `yaml` files were edited more recently. I'll go ahead and copy over the descriptions to the `md` to not lose them

**Comment by junhouse** [comment]
> > nice, looking good! Were you able to verify that the `mdx` files and `description` section of the open API are the same?
> 
> Almost all of them are the same or the `description` section of the open API is a subset of the content in the `mdx` files with three exceptions: `Query Retention Report`, `Query Profiles`, and `JQL`
> 
> Synced with Myron, MD should be the source of truth for most files but it seems that for these three exceptions the `yaml` files were edited more recently. I'll go ahead and copy over the descriptions to the `md` to not lose them

Thanks for being so thorough!

**Review by junhouse — APPROVED** [review]
Thanks for this work! LGTM

**Pull request merged**
