### PR TITLE
Add Docs AI and Search

### PR DESCRIPTION
**Pull request by ishamehramixpanel**

### CODE REVIEW

**Review by ishamehramixpanel — COMMENTED** [review]
changing the case of the properties

**Review by ishamehramixpanel — COMMENTED** [review]
delete other search

**Comment by mherrman** [comment]
Not sure if this was ready to go? The search in preview doesnt seem to work but dunno if that a preview thing or what

**Comment by ishamehramixpanel** [comment]
Not ready quite yet

**Review by junhouse — APPROVED** [review]

**Pull request merged**
