### PR TITLE
Remove beta tags for Session Replay Web

### PR DESCRIPTION
**Pull request by jakewski**

### CODE REVIEW

**Review by carlosdanieltt — APPROVED** [review]
Looks good!

**Comment by Tofufu** [comment]
To confirm, we're looking to remove all the "Beta" info for Session Replay - Web, is that correct?

Everything in the PR looks good - there are still parts of the Session Replay - Web Doc page though that mention web as beta:

1. https://github.com/mixpanel/docs/blob/main/pages/docs/session-replay/_meta.json
^ I believe we need to re-label
image

2. In FAQ section there currently is still: "As of today, Session Replay is in closed Beta testing for web-based applications (including mobile web)"

**Comment by jakewski** [comment]
> 9081aff

Thanks for catching! Updated those two here https://github.com/mixpanel/docs/pull/1418/commits/9081aff8f2c5be0533a580046cff3fc977e88e41

**Review by Tofufu — APPROVED** [review]
lgtm!

**Pull request merged**
