### PR TITLE
Update advanced.md

### PR DESCRIPTION
**Pull request by dorothy-koh**
Moved "Move Board" section to Boards -> Advanced, so no longer need to show it here.

### CODE REVIEW

**Comment by mherrman** [comment]
@dorothy-koh I wasnt seeing that text block in the Boards -> Advanced section in the preview. Was it added in another branch or this one?

**Comment by mavlee** [comment]
this change should be a part of 
https://github.com/mixpanel/docs/pull/773

so it all gets deployed at once

i would recommend closing this PR, and putting the changes into the PR of 773

**Comment by mherrman** [comment]
Hey @dorothy-koh see Mavs comment above. It wold be good to put the removal and addition of text into a single PR so we know both happen at the same time. Lmk if you would be ok to do that or if you needed any help with it

**Comment by dorothy-koh** [comment]
Noted on this, sorry never changed two files at once before. Thanks @mherrman for offering to help! 

I've updated #773 , closing this PR.

**Pull request closed without merging**
